-- --- FASE 4: AUTOMATIZACIÓN E INTELIGENCIA ---
-- Proyecto: Doc-Tracker Pepsicargo
-- Objetivo: Triggers de notificaciones y vistas para Power BI.

-- 1. TABLA PARA ALERTAS INTERNAS
CREATE TABLE IF NOT EXISTS alertas_vencimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa_id TEXT REFERENCES vh_maestro(placa),
    tipo_documento TEXT,
    dias_restantes INTEGER,
    fecha_alerta TIMESTAMP WITH TIME ZONE DEFAULT now(),
    estado_notificacion TEXT DEFAULT 'PENDIENTE'
);

-- 2. FUNCIÓN DE TRIGGER PARA DETECTAR VENCIMIENTOS
CREATE OR REPLACE FUNCTION fn_track_vencimientos()
RETURNS TRIGGER AS $$
DECLARE
    dias_restantes INTEGER;
BEGIN
    dias_restantes := NEW.fecha_vencimiento - CURRENT_DATE;

    -- Alerta 15 días antes
    IF dias_restantes = 15 THEN
        INSERT INTO alertas_vencimiento (placa_id, tipo_documento, dias_restantes)
        VALUES (NEW.placa_id, NEW.tipo_documento, 15);
    END IF;

    -- Alerta 5 días antes
    IF dias_restantes = 5 THEN
        INSERT INTO alertas_vencimiento (placa_id, tipo_documento, dias_restantes)
        VALUES (NEW.placa_id, NEW.tipo_documento, 5);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. TRIGGER SOBRE vh_documentos
DROP TRIGGER IF EXISTS tr_vencimientos_documentos ON vh_documentos;
CREATE TRIGGER tr_vencimientos_documentos
AFTER INSERT OR UPDATE ON vh_documentos
FOR EACH ROW EXECUTE FUNCTION fn_track_vencimientos();

-- 4. VISTAS PARA POWER BI (Weekly Digest & BI Integration)

-- Ranking de Cumplimiento por Sede
CREATE OR REPLACE VIEW vista_cumplimiento_sedes AS
SELECT 
    v.sede_id,
    COUNT(v.placa) as total_vehiculos,
    COUNT(d.id) FILTER (WHERE d.fecha_vencimiento > CURRENT_DATE) as documentos_al_dia,
    COUNT(d.id) FILTER (WHERE d.fecha_vencimiento <= CURRENT_DATE) as documentos_vencidos,
    ROUND((COUNT(d.id) FILTER (WHERE d.fecha_vencimiento > CURRENT_DATE)::NUMERIC / NULLIF(COUNT(d.id), 0)) * 100, 2) as porcentaje_cumplimiento
FROM vh_maestro v
LEFT JOIN vh_documentos d ON v.placa = d.placa_id
GROUP BY v.sede_id;

-- Vista Global de Vehículos Bloqueados
CREATE OR REPLACE VIEW vista_vehiculos_bloqueados AS
SELECT 
    v.placa,
    v.categoria,
    v.sede_id,
    d.tipo_documento,
    d.fecha_vencimiento
FROM vh_maestro v
JOIN vh_documentos d ON v.placa = d.placa_id
WHERE d.fecha_vencimiento <= CURRENT_DATE;

-- --- FIN AUTOMATIZACIÓN ---
