-- --- MASTER INTEGRATION SQL: Doc-Tracker Pepsicargo ---
-- Consolidación de Fases 1, 2, 3 y 4.
-- Ejecutar en el Editor SQL de Supabase.

-- 1. TIPOS ENUMERADOS
DO $$ BEGIN
    CREATE TYPE rol_usuario AS ENUM ('SUPER_ADMIN', 'GESTOR_PROPIOS', 'GESTOR_PEPSICARGO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE categoria_vh AS ENUM ('PEPSICARGO', 'PROPIA', 'CORP');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE fuente_documento AS ENUM ('RUNT', 'MANUAL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 2. TABLAS

-- perfiles_usuario
CREATE TABLE IF NOT EXISTS perfiles_usuario (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    rol rol_usuario NOT NULL DEFAULT 'GESTOR_PEPSICARGO',
    correo_corporativo TEXT UNIQUE NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- vh_maestro
CREATE TABLE IF NOT EXISTS vh_maestro (
    placa TEXT PRIMARY KEY,
    nit_cedula TEXT NOT NULL,
    categoria categoria_vh NOT NULL,
    marca TEXT,
    modelo INTEGER,
    sede_id TEXT,
    vin TEXT,
    numero_motor TEXT,
    numero_chasis TEXT,
    color TEXT,
    capacidad_carga NUMERIC,
    ejes INTEGER,
    peso_bruto NUMERIC,
    fecha_matricula_inicial DATE,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- vh_documentos
CREATE TABLE IF NOT EXISTS vh_documentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa_id TEXT REFERENCES vh_maestro(placa) ON DELETE CASCADE NOT NULL,
    tipo_documento TEXT NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    fuente fuente_documento DEFAULT 'MANUAL' NOT NULL,
    estado TEXT DEFAULT 'ACTIVO',
    url_soporte TEXT, -- Para Supabase Storage
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- logs_auditoria
CREATE TABLE IF NOT EXISTS logs_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID REFERENCES auth.users(id),
    tabla_afectada TEXT NOT NULL,
    accion TEXT NOT NULL,
    detalle_cambio JSONB,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- alertas_vencimiento
CREATE TABLE IF NOT EXISTS alertas_vencimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa_id TEXT REFERENCES vh_maestro(placa),
    tipo_documento TEXT,
    dias_restantes INTEGER,
    fecha_alerta TIMESTAMP WITH TIME ZONE DEFAULT now(),
    estado_notificacion TEXT DEFAULT 'PENDIENTE'
);

-- 3. SEGURIDAD (RLS)

ALTER TABLE perfiles_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE vh_maestro ENABLE ROW LEVEL SECURITY;
ALTER TABLE vh_documentos ENABLE ROW LEVEL SECURITY;

-- Políticas RLS: vh_maestro
DROP POLICY IF EXISTS policy_gestor_pepsicargo_select ON vh_maestro;
CREATE POLICY policy_gestor_pepsicargo_select ON vh_maestro FOR SELECT USING (
    (SELECT rol FROM perfiles_usuario WHERE id = auth.uid()) = 'GESTOR_PEPSICARGO' AND categoria = 'PEPSICARGO'
);

DROP POLICY IF EXISTS policy_gestor_propios_select ON vh_maestro;
CREATE POLICY policy_gestor_propios_select ON vh_maestro FOR SELECT USING (
    (SELECT rol FROM perfiles_usuario WHERE id = auth.uid()) = 'GESTOR_PROPIOS' AND categoria IN ('PROPIA', 'CORP')
);

DROP POLICY IF EXISTS policy_super_admin_all ON vh_maestro;
CREATE POLICY policy_super_admin_all ON vh_maestro FOR ALL USING (
    (SELECT rol FROM perfiles_usuario WHERE id = auth.uid()) = 'SUPER_ADMIN'
);

-- 4. DISPARADORES Y AUTOMATIZACIÓN

CREATE OR REPLACE FUNCTION fn_track_vencimientos()
RETURNS TRIGGER AS $$
DECLARE
    dias_restantes INTEGER;
BEGIN
    dias_restantes := NEW.fecha_vencimiento - CURRENT_DATE;
    IF dias_restantes IN (5, 15) THEN
        INSERT INTO alertas_vencimiento (placa_id, tipo_documento, dias_restantes)
        VALUES (NEW.placa_id, NEW.tipo_documento, dias_restantes);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_vencimientos_documentos ON vh_documentos;
CREATE TRIGGER tr_vencimientos_documentos AFTER INSERT OR UPDATE ON vh_documentos FOR EACH ROW EXECUTE FUNCTION fn_track_vencimientos();

-- 5. VISTAS BI
CREATE OR REPLACE VIEW vista_cumplimiento_sedes AS
SELECT v.sede_id, COUNT(v.placa) as total_vh, ROUND(AVG(CASE WHEN d.fecha_vencimiento > CURRENT_DATE THEN 100 ELSE 0 END), 2) as cumplimiento
-- 6. POLÍTICAS DE STORAGE (Supabase Storage)
-- El bucket 'documentos_flota' debe ser creado manualmente en la interfaz de Supabase.
-- Aquí definimos el acceso controlado.

INSERT INTO storage.buckets (id, name, public) VALUES ('documentos_flota', 'documentos_flota', false) 
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Acceso selectivo por rol" ON storage.objects;
CREATE POLICY "Acceso selectivo por rol" ON storage.objects
FOR ALL USING (
    auth.role() = 'authenticated' -- Acceso base para autenticados, RLS en tablas protege la metadata
);
