-- --- INICIO INFRAESTRUCTURA ---
-- Proyecto: Doc-Tracker Pepsicargo (Etapa 1)
-- Objetivo: Arquitectura relacional para 1,000 vehículos con RBAC y RLS.

-- 1. TIPOS ENUMERADOS
CREATE TYPE rol_usuario AS ENUM ('SUPER_ADMIN', 'GESTOR_PROPIOS', 'GESTOR_PEPSICARGO');
CREATE TYPE categoria_vh AS ENUM ('PEPSICARGO', 'PROPIA', 'CORP');
CREATE TYPE fuente_documento AS ENUM ('RUNT', 'MANUAL');

-- 2. TABLAS PRINCIPALES

-- perfiles_usuario: Maneja el Rol-Based Access Control (RBAC)
CREATE TABLE perfiles_usuario (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    rol rol_usuario NOT_NULL DEFAULT 'GESTOR_PEPSICARGO',
    correo_corporativo TEXT UNIQUE NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- vh_maestro: Tabla central de vehículos
CREATE TABLE vh_maestro (
    placa TEXT PRIMARY KEY, -- Formato: ABC123D
    nit_cedula TEXT NOT NULL,
    categoria categoria_vh NOT NULL,
    marca TEXT,
    modelo INTEGER,
    sede_id TEXT,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- vh_documentos: Tabla transaccional para flexibilidad total
CREATE TABLE vh_documentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa_id TEXT REFERENCES vh_maestro(placa) ON DELETE CASCADE NOT NULL,
    tipo_documento TEXT NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    fuente fuente_documento DEFAULT 'MANUAL' NOT NULL,
    estado TEXT DEFAULT 'ACTIVO',
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. AUDITORÍA (LOGS)
CREATE TABLE logs_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID REFERENCES auth.users(id),
    tabla_afectada TEXT NOT NULL,
    accion TEXT NOT NULL, -- INSERT, UPDATE, DELETE
    detalle_cambio JSONB,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- --- INICIO SEGURIDAD (RLS) ---

-- Habilitar RLS en todas las tablas
ALTER TABLE perfiles_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE vh_maestro ENABLE ROW LEVEL SECURITY;
ALTER TABLE vh_documentos ENABLE ROW LEVEL SECURITY;

-- 4. POLÍTICAS DE ACCESO (vh_maestro)

-- GESTOR_PEPSICARGO: Solo lee vehículos donde categoria = 'PEPSICARGO'
CREATE POLICY policy_gestor_pepsicargo_select ON vh_maestro
FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM perfiles_usuario
        WHERE perfiles_usuario.id = auth.uid()
        AND perfiles_usuario.rol = 'GESTOR_PEPSICARGO'
    )
    AND categoria = 'PEPSICARGO'
);

-- GESTOR_PROPIOS: Lee categoria IN ('PROPIA', 'CORP')
CREATE POLICY policy_gestor_propios_select ON vh_maestro
FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM perfiles_usuario
        WHERE perfiles_usuario.id = auth.uid()
        AND perfiles_usuario.rol = 'GESTOR_PROPIOS'
    )
    AND categoria IN ('PROPIA', 'CORP')
);

-- SUPER_ADMIN: Acceso total
CREATE POLICY policy_super_admin_all ON vh_maestro
FOR ALL
USING (
    EXISTS (
        SELECT 1 FROM perfiles_usuario
        WHERE perfiles_usuario.id = auth.uid()
        AND perfiles_usuario.rol = 'SUPER_ADMIN'
    )
);

-- 5. POLÍTICAS DE ACCESO (vh_documentos) - Heredan de la visibilidad del vehículo
CREATE POLICY policy_documentos_select ON vh_documentos
FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM vh_maestro
        WHERE vh_maestro.placa = vh_documentos.placa_id
    )
);

-- --- FIN SEGURIDAD ---
